### ISSUE TITLE
CSRF Token ?

### ISSUE THREAD

**Issue by Romaixn** [aleksblendwerk/pingcrm-symfony#5]
Hey ! Thanks for this repo !

I try to integrate InertiaJS on my side but I have a problem with CSRF token. (Invalid CSRF token.)
How did you manage the CSRFs on the forms?

Thanks

**Comment by aleksblendwerk** [comment]
It's been a while since I have last seen this project of mine and I'd need to look into it again to see if CSRF is actually enabled or if I just skipped it because other things were more important to me for this proof of concept.

This package should be a good lead though, at least it's required in this project and there is some configuration for it in `config/routes/annotations.yaml`: https://github.com/dneustadt/DneustadtCsrfCookieBundle

I hope this helps!

**Comment by Romaixn** [comment]
I was missing this bundle! Thanks a lot for your help !
